on:
  push:
    branches:
      - main
name: release-please
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{secrets.GOOGLEWORKSPACE_BOT_TOKEN}}
          release-type: node
          package-name: apps-script-oauth1
      - uses: ./.github/workflows/deploy
        if: ${{ steps.release.outputs.release_created }}
