on: [pull_request]
name: Update dist folder
jobs:
  update-dist-src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Generate dist
        run: npm run dist
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update dist/ and docs/ directories"
          commit_user_name: Google Workspace Bot
          commit_user_email: googleworkspace-bot@google.com
          commit_author: Google Workspace Bot <googleworkspace-bot@google.com>
